# Generated by Django 5.0.6 on 2024-05-18 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dehleezapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dehleezapp.category",
            ),
        ),
    ]
