# Generated by Django 5.0.6 on 2024-05-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dehleezapp", "0004_alter_category_image_productimages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimages",
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "product images",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
